### PR TITLE
LiteSpeed Cache compatability

### PR DESCRIPTION
**Pull request by dmitry-christie**
Issue #167.

### CODE REVIEW

**Comment by dcooney** [comment]
Thanks @dmitry-christie 
I'm not familiar with `wp_script_add_data`. Could this addition have any side effects to be concerned about? Or is this specific for LiteSpeed Cache?

**Comment by dmitry-christie** [comment]
@dcooney It is only specific to LS Cache. No problem :)

**Comment by dcooney** [comment]
`data-no-optimize` is a LiteSpeed Cache thing?

**Comment by dmitry-christie** [comment]
Yes, that's what I meant. Sorry. This should exclude the script from minification, since it is already minified.

**Comment by dcooney** [comment]
Thanks. Merged.

**Pull request merged**
